library(dplyr)
demo_table1 <- read.csv(file ='MechaCar_mpg.csv', check.names=F, stringsAsFactors = F)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,demo_table1)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,demo_table1))

demo_table <- read.csv(file ='Suspension_Coil.csv', check.names=F, stringsAsFactors = F)
library(tidyverse)
summarize_demo <- demo_table %>%summarise(Mean = mean(PSI), Median = median(PSI), Variance = var(PSI), SD = sd(PSI))
summarise_demo <- demo_table %>% group_by(Manufacturing_Lot) %>%summarise(Mean = mean(PSI), Median = median(PSI), Variance = var(PSI), SD = sd(PSI), .groups = 'keep')

sample_table <- demo_table %>% sample_n(50)
t.test((sample_table$PSI), mu = (mean(demo_table$PSI)))
newdata1 <- subset(demo_table, Manufacturing_Lot == "Lot1", select = PSI)
newdata2 <- subset(demo_table, Manufacturing_Lot == "Lot2", select = PSI)
newdata3 <- subset(demo_table, Manufacturing_Lot == "Lot3", select = PSI)
sample_table1 <- newdata1 %>% sample_n(50)
sample_table2 <- newdata2 %>% sample_n(50)
sample_table3 <- newdata3 %>% sample_n(50)
t.test((sample_table1$PSI), mu = (mean(newdata1$PSI)))
t.test((sample_table2$PSI), mu = (mean(newdata2$PSI)))
t.test((sample_table3$PSI), mu = (mean(newdata3$PSI)))
